name: Новая тема
description: Предложить новую тему для документации
title: "[NEW TOPIC] "
labels: ["enhancement", "documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Спасибо за предложение новой темы! Пожалуйста, заполните форму ниже.
  
  - type: textarea
    id: goal
    attributes:
      label: Цель
      description: Что нужно решить или объяснить?
      placeholder: Например: "Как автоматизировать создание отчётов в E3D"
    validations:
      required: true
  
  - type: dropdown
    id: section
    attributes:
      label: Раздел
      description: В каком разделе должна быть статья?
      options:
        - getting-started
        - how-to
        - reference
        - recipes
        - glossary
    validations:
      required: true
  
  - type: input
    id: tags
    attributes:
      label: Теги
      description: Предлагаемые теги через запятую
      placeholder: pml, automation, e3d
    validations:
      required: false
  
  - type: textarea
    id: expected-result
    attributes:
      label: Ожидаемый результат
      description: Что должен получить читатель после прочтения?
      placeholder: "Пошаговое руководство с проверяемым результатом"
    validations:
      required: true
  
  - type: textarea
    id: links
    attributes:
      label: Ссылки
      description: Полезные ссылки на официальную документацию или ресурсы
      placeholder: "https://..."
    validations:
      required: false 